SQUASHME! [VPG]: drm: Fix warning in drm_mode_obj_set_property_ioctl, drm_crtc.c
Not terminating string in same line generates compilation error
when warnings are treated as errors. This patch resolves this
compilation issue in drivers/gpu/drm/drm_crtc.c:4200:4:
error: missing terminating " character
    DRM_DEBUG_KMS("CRTC from connector,CRTC={id=%d props=

This patch should be squashed into the following patch:

commit 4feccbbe33cf56e0f4e75e58f12c1961d42669b5
Change-Id: I73e94c6541f4621d86371cadd580dcdfc33c50d3
Author: Akashdeep Sharma <akashdeep.sharma@intel.com>
Date:   Mon Jun 1 19:23:30 2015 +0530
    SQUASHME! [VPG]: drm: Use right level of log message in set property ioctl

Change-Id: I3350870975434812e9672043bd3907a3949053c9
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-4749
Signed-off-by: Akashdeep Sharma <akashdeep.sharma@intel.com>
Signed-off-by: Shubhangi Shrivastava <shubhangi.shrivastava@intel.com>